
# These are supported funding model platforms

github: [char0n]
patreon: char0n
open_collective: ramda-adjunct
ko_fi: char0n
tidelift: npm/ramda-adjunct
community_bridge: cf59a185-1f1c-4c1c-9533-222ee8be9678
liberapay: char0n
issuehunt: char0n
# otechie: # Replace with a single Otechie username
