# action.yml
name: 'Swagger Editor Validator'
description: 'Validates OpenAPI 2.x/3.x definition file'
inputs:
  swagger-editor-url:
    description: 'URL where Swagger Editor is served'
    required: false
    default: 'https://editor.swagger.io/'
  definition-file:
    description: 'Path to definition file'
    required: true
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
    - run: SWAGGER_EDITOR_URL=${{ inputs.swagger-editor-url }} DEFINITION_FILE=${{ inputs.definition-file }} node index.js
      shell: bash
