# action.yml
name: 'Swagger Editor Validator'
description: 'Validates OpenAPI 2.x/3.x definition file'
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
    - run: node index.js
      shell: bash
