# action.yml
name: Swagger Editor Validator Pluto
description: This GitHub Actions validates OpenAPI (OAS) definition file using Swagger Editor.
inputs:
  swagger-editor-url:
    description: URL where Swagger Editor is served
    required: false
    default: https://editor.swagger.io/
  definition-file:
    description: Path to definition file
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - run: npm install
      shell: bash
    - run: SWAGGER_EDITOR_URL=${{ inputs.swagger-editor-url }} DEFINITION_FILE=${{ inputs.definition-file }} node src/index.js
      shell: bash
branding:
  icon: "file-text"
  color: "green"
