on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello

    steps:
      - uses: actions/checkout@v2
      - uses: docker://swaggerapi/swagger-editor
        env:
          SWAGGER_FILE: "examples/openapi-3-0-1.yaml"
        run: node index.js
